project:
  type: website
  output-dir: out
  resources:
    - /data/news-stats-postcodes-long.csv
  
# only re-render if the source changes or if we specifically render that file
execute:
  freeze: auto
